name: Test
on:
  push:

  pull_request:

jobs:

  linux:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - uses: actions/checkout@v2

    - run: (cd ~ && GO111MODULE=on go get github.com/ysmood/kit/cmd/godev)

    - run: godev -l -m 100
