name: Test
on:
  push:

  pull_request:

jobs:

  linux:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - uses: actions/checkout@v2

    - name: test
      run: |
        (cd ~ && GO111MODULE=on go get github.com/ysmood/kit/cmd/godev)
        godev -l -m 100

    - uses: codecov/codecov-action@v1
